INSERT INTO producto (nombre, precio, cantidad, categoria, descripcion, foto)
VALUES ('BaconQueso', 3.5, 34, 1, 'Un bocadillo de bacon y queso', 'baconqueso.jpg'),
        ('Calamares', 3.5, 34, 1, 'Un bocadillo de calamares', 'calamares.jpg'),
        ('LomoQueso', 3.5, 34, 1, 'Un bocadillo de lomo y queso', 'lomoqueso.jpg'),
        ('TortillaPatata', 3, 34, 1, 'Nada mejor que tortilla de patata, en formato bocadillo', 'tortillapatata.jpg'),
        ('Jamon', 3.5, 34, 1, '¿De todo el menu, vienes y pides un bocadillo de jamon? En serio?', 'jamon.jpg'),
        ('Chorizo', 3.5, 34, 1, 'El clasico, un bocadillo de chorizo', 'chorizo.jpg'),
        ('Longaniza', 3.5, 34, 1, 'Menos clasico, pero igual de bueno, la verdad no puedo decir que no a un bocadillo de longaniza', 'longaniza.jpg'),
        ('Pechuga', 3.5, 34, 1, 'Pechuga en un bocadillo, pan dentro de pan?!?', 'pechuga.jpg'),
        ('MiniBocadillo', 3.5, 34, 1, 'Coges un bocadillo, y le reduces su variable size un 28%', 'minibocadillo.jpg'),
        ('MitadBocadillo', 3.5, 34, 1, 'Un bocadillo, pero muy, MUY reducido', 'mitadbocadillo.jpg'),
        ('CafeSoloDescaf', 1.1, 31, 2, 'Un cafe descafeinado, sin ningun extra', 'cafedescaf.jpg'),
        ('CafeCortado', 1.1, 31, 2, 'Un cafecito cortado, por favor', 'cafecortado.jpg'),
        ('CafeCortadoDescaf', 1.1, 31, 2, 'Cafe cortado, pero descafeinado', 'cafecortadodescaf.jpg'),
        ('CafeConLeche', 1.1, 31, 2, 'Otro clasico, el cafe con leche', 'cafeconleche.jpg'),
        ('CafeConLecheDescaf', 1.1, 31, 2, 'Un cafe, con leche, y descafeinado, pues vale', 'cafeconlechedescaf.jpg'),
        ('PoleoMenta', 1.1, 31, 2, '¿Un poleo menta? ¿Perdona?', 'poleomenta.jpg'),
        ('Manzanilla', 1.1, 31, 2, '¿Una manzanilla, pero porque?', 'manzanilla.jpg'),
        ('TeNegro', 1.1, 31, 2, 'A black tea please', 'tenegro.jpg'),
        ('TeVerde', 1.1, 31, 2, 'A green tea sir', 'teverde.jpg'),
        ('Croissant', 1.1, 31, 3, 'Un croissant, otro clasico', 'croissant.jpg'),
        ('NapolitanaChocolate', 1.1, 31, 3, 'Una napolitana, rebosante de chocolate, yo lo pediria 11/10 veces', 'napolitanachocolate.jpg'),
        ('NapolitanaCrema', 1.1, 31, 3, 'Este en vez de 11/10 veces, lo pido 9/10', 'napolitanacrema.jpg'),
        ('Tostada', 1.1, 31, 3, 'Nada mejor que una tostada para un descanso', 'tostada.jpg'),
        ('CoktailFrutosSecos', 1.1, 31, 4, '¿Vienes aqui para pedir frutos secos? Yo los habria comprado en un Mercadona, o cualquier otro supermercado', 'coktailfrutossecos.jpg'),
        ('BolsaPatatas', 1.1, 31, 4, '¿Bolsa de patatas para picar, pero no son de la marca Campesino? Paso', 'bolsapatatas.jpg'),
        ('Pringles', 1.1, 31, 4, 'Oye, que te apetece tomar en una cafeteria, Ehhh, una bolsa de Pringles', 'pringles.jpg'),
        ('MaizPequeno', 1.1, 31, 4, '¿Un maiz pequeno? Pues vale', 'maizpequeno.jpg'),
        ('MaizGrande', 1.1, 31, 4, '¿Ahora el maiz es grande? Bueno pues adelante, no te puedo parar si lo quieres pedir', 'maizgrande.jpg'),
        ('BarritaMuesly', 1.1, 31, 4, 'Una barrita muesly, por favor', 'barritamuesly.jpg'),
        ('KitKat', 1.1, 31, 4, 'Como diabetico, no pediria los KitKat, que estan repletos de glucosa, pero bueno, estan ricos asi que si los pides, yo lo entiendo', 'kitkat.jpg'),
        ('Filipinos', 1.1, 31, 4, 'Fino fino fino filipino', 'filipinos.jpg'),
        ('Mikado', 1.1, 31, 4, 'Igual que los KitKat, si los quieres, adelante', 'mikado.jpg'),
        ('ChipsAhoy', 1.1, 31, 4, 'Ahoy mate, gimme those Chips right now', 'chipsahoy.jpg'),
        ('Agua', 1.1, 31, 5, '¿Una botella de agua? A ver, no te voy a decir que no, todos necesitamos agua, pero no seria lo primero que pediria de este menu, la verdad', 'agua.jpg'),
        ('Batido', 1.1, 31, 5, 'Dependiendo del sabor del batido, te gustara mas o menos', 'batido.jpg'),
        ('ZumoMinutMaid', 1.1, 31, 5, '¿Un Que?, Me estoy haciendo mas preguntas sobre el nombre de este producto', 'zumominutmaid.jpg'),
        ('RefrescosLata', 1.1, 31, 5, 'Un refresco? Me apunto (si es sin azucar claro esta)', 'refrescoslata.jpg'),
        ('Coca Cola Zero', 1.7, 28, 5, 'Una Coca Cola sin azucares (por favor compra 17 de estas, que siempre las necesito)', 'cocacolazero.jpg'),
        ('Coca Cola Zero Zero', 1.7, 28, 5, 'Una Coca Cola sin azucares y sin cafeina (sin cafeina ya no cunden tanto en mi opinion)', 'cocacolazerozero.jpg'),
        ('FantaNaranja', 1.1, 31, 5, 'Las fontas, otro clasico (espera un momento he dicho fontas? Queria decir fantas, maldito Fontaine)', 'fantanaranja.jpg'),
        ('FantaLimon', 1.1, 31, 5, 'Por curiosidad, si la pides zero, veras que tiene nada de hidratos de carbono, pero la de naranja, aunque sea zero, sigue teniendo hidratos', 'fantalimon.jpg'),
        ('Nestea', 1.1, 31, 5, 'El favorito de un Alejandro Tesan, nunca le dice no a un Nestea', 'nestea.jpg'),
        ('ZumoSabores', 1.1, 31, 5, '¿Sabores?, ¿Que sabores? Eso lo tendras que descubrir tu', 'zumosabores.jpg'),
        ('Mosto', 1.1, 31, 5, 'Oye chaval, quiero un mosto ipso facto', 'mosto.jpg'),
        ('CervezaSinAlcohol', 1.1, 31, 5, '¿Una cerveza? ¿En un colegio?, Vale que sea sin alcohol pero... creo que no la pediria, sobre todo si estan los de Infantil por la cafeteria', 'cervezasinalcohol.jpg'),
        ('FrutaTemporada', 1.1, 31, 6, 'Una fruta de temporada, sea cual sea, yo la pediria', 'frutatemporada.jpg'),
        ('YogurMuesli', 1.1, 31, 6, 'El yogur favorito de Messi, el Muesli', 'yogurmuesli.jpg');
INSERT INTO usuario (username, pwd, tipousuario) VALUES ('admin', 'admin', 1);
INSERT INTO usuario (username, pwd, tipousuario) VALUES ('JMVT', 'JMVT', 2);
INSERT INTO usuario (username, pwd, tipousuario) VALUES ('CVT', 'CVT', 2);
INSERT INTO pedidos (username, productos, producto_cantidad, total) VALUES ('hola', 'CocaCola', '3', 4);